name: Scheduled deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      # - name: Check environment variables
      #   run: echo $QIITA_ACCESS_TOKEN $NEXT_PUBLIC_MICROCMS_API_URL $NEXT_PUBLIC_MICROCMS_API_KEY
      #   env:
      #     QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
      #     MICROCMS_API_URL: ${{ secrets.MICROCMS_API_URL }}
      #     MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
      - name: Run build
        # env:
        #   QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
        #   MICROCMS_API_URL: ${{ secrets.MICROCMS_API_URL }}
        #   MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
        run: npm run build
  ci:
    name: ci
    runs-on: ubuntu-latest
    needs: build
    # env:
    #   VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    #   VITE_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: install
        run: npm i
      - name: test
        run: npm run test
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js and cache
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - name: Install firebase-tools
        run: npm install --save-dev firebase-tools
      - name: Decode Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV
      - name: change space
        run: ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Deploy to Firebase Hosting
        run: |
          ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      - name: delete GOOGLE_APPLICATION_CREDENTIALS
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}
