name: Scheduled deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Check environment variables
        run: echo $QIITA_API_TOKEN $MICROCMS_API_URL $MICROCMS_API_KEY
        env:
          QIITA_API_TOKEN: ${{ secrets.QIITA_API_TOKEN }}
          QIITA_USER_ID: ${{ secrets.QIITA_USER_ID }}
          MICROCMS_API_URL: ${{ secrets.MICROCMS_API_URL }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
      - name: Run build
        env:
          QIITA_API_TOKEN: ${{ secrets.QIITA_API_TOKEN }}
          QIITA_USER_ID: ${{ secrets.QIITA_USER_ID }}
          MICROCMS_API_URL: ${{ secrets.MICROCMS_API_URL }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
        run: npm run build
  ci:
    name: ci
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: install
        run: npm i
      - name: test
        run: npm run test
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install firebase-tools globally
        run: npm install -g firebase-tools
      - name: Decode Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV
      - name: Create .env file and select Firebase project
        run: |
          touch .env
          echo "QIITA_USER_ID=${{ secrets.QIITA_USER_ID }}" >> .env
          echo "MICROCMS_API_KEY=${{ secrets.MICROCMS_API_KEY }}" >> .env
          echo "QIITA_API_TOKEN=${{ secrets.QIITA_API_TOKEN }}" >> .env
          echo "MICROCMS_API_URL=${{ secrets.MICROCMS_API_URL }}" >> .env
          firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting,functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          QIITA_API_TOKEN: ${{ secrets.QIITA_API_TOKEN }}
          QIITA_USER_ID: ${{ secrets.QIITA_USER_ID }}
          MICROCMS_API_URL: ${{ secrets.MICROCMS_API_URL }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
      - name: Delete Firebase service account key
        run: rm ./firebase-key.json
        if: always()
